### ISSUE TITLE
Documentation should mention to not set config

### ISSUE THREAD

**Issue by kurtisnelson** [thoughtbot/fake_braintree#78]
The README should note that you have to not set *any* of the braintree config values for it to work.

**Comment by gabebw** [comment]
Sure, I can update it - what configuration did you set exactly?

**Comment by kurtisnelson** [comment]
```ruby
unless Rails.env.test?
    Braintree::Configuration.environment = :sandbox
    Braintree::Configuration.merchant_id = ENV['BRAINTREE_ID']
    Braintree::Configuration.public_key = ENV['BRAINTREE_PUBLIC_KEY']
    Braintree::Configuration.private_key = ENV['BRAINTREE_PRIVATE_KEY']
end
```

**Comment by gabebw** [comment]
Ah, great. Thank you.

**Comment by gabebw** [comment]
I think that the only thing that messes with fake_braintree is setting `Braintree::Configuration.environment = :sandbox`. If you set everything else, but don't set that, does it work? I want to be as specific as possible in the docs.

**Comment by kurtisnelson** [comment]
Yep, that did it.

**Comment by gabebw** [comment]
How's this look: #79
