### ISSUE TITLE
Braintree::UnexpectedError: expected a gzipped response

### ISSUE THREAD

**Issue by CucumisSativus** [thoughtbot/fake_braintree#85]
While using fake_braintree, every action which creates a braintree request fails due to `Braintree::UnexpectedError: expected a gzipped response`. Although this may look like #48 i don't use redirects but instead server-to-server api. 

How to reproduce this problem:
```ruby
require 'fake_braintree'
FakeBraintree.activate!
result = Braintree::Customer.create(
    :credit_card => {
     :payment_method_nonce => Braintree::Test::Nonce::Transactable,
     :options => {
       :verify_card => true
     }
  }
)
```

And the backtrace
```ruby
NoMethodError - undefined method `[]' for nil:NilClass:
	/Users/michal/.rvm/gems/ruby-2.1.5@my_gemset/gems/fake_braintree-0.6.0/lib/fake_braintree/customer.rb:113:in `generate_credit_cards_from'
	/Users/michal/.rvm/gems/ruby-2.1.5@my_gemset/gems/fake_braintree-0.6.0/lib/fake_braintree/customer.rb:66:in `customer_hash'
	/Users/michal/.rvm/gems/ruby-2.1.5@my_gemset/gems/fake_braintree-0.6.0/lib/fake_braintree/customer.rb:82:in `invalid_credit_card?'
	/Users/michal/.rvm/gems/ruby-2.1.5@my_gemset/gems/fake_braintree-0.6.0/lib/fake_braintree/customer.rb:49:in `invalid?'
	/Users/michal/.rvm/gems/ruby-2.1.5@my_gemset/gems/fake_braintree-0.6.0/lib/fake_braintree/customer.rb:16:in `create'
	/Users/michal/.rvm/gems/ruby-2.1.5@my_gemset/gems/fake_braintree-0.6.0/lib/fake_braintree/sinatra_app.rb:25:in `block in <class:SinatraApp>'
	/Users/michal/.rvm/gems/ruby-2.1.5@my_gemset/gems/sinatra-1.4.5/lib/sinatra/base.rb:1603:in `call'
	/Users/michal/.rvm/gems/ruby-2.1.5@my_gemset/gems/sinatra-1.4.5/lib/sinatra/base.rb:1603:in `block in compile!'
	/Users/michal/.rvm/gems/ruby-2.1.5@my_gemset/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `[]'
	/Users/michal/.rvm/gems/ruby-2.1.5@my_gemset/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `block (3 levels) in route!'
	/Users/michal/.rvm/gems/ruby-2.1.5@my_gemset/gems/sinatra-1.4.5/lib/sinatra/base.rb:985:in `route_eval'
	/Users/michal/.rvm/gems/ruby-2.1.5@my_gemset/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `block (2 levels) in route!'
	/Users/michal/.rvm/gems/ruby-2.1.5@my_gemset/gems/sinatra-1.4.5/lib/sinatra/base.rb:1006:in `block in process_route'
	/Users/michal/.rvm/gems/ruby-2.1.5@my_gemset/gems/sinatra-1.4.5/lib/sinatra/base.rb:1004:in `catch'
	/Users/michal/.rvm/gems/ruby-2.1.5@my_gemset/gems/sinatra-1.4.5/lib/sinatra/base.rb:1004:in `process_route'
	/Users/michal/.rvm/gems/ruby-2.1.5@my_gemset/gems/sinatra-1.4.5/lib/sinatra/base.rb:964:in `block in route!'
	/Users/michal/.rvm/gems/ruby-2.1.5@my_gemset/gems/sinatra-1.4.5/lib/sinatra/base.rb:963:in `each'
	/Users/michal/.rvm/gems/ruby-2.1.5@my_gemset/gems/sinatra-1.4.5/lib/sinatra/base.rb:963:in `route!'
	/Users/michal/.rvm/gems/ruby-2.1.5@my_gemset/gems/sinatra-1.4.5/lib/sinatra/base.rb:1076:in `block in dispatch!'
	/Users/michal/.rvm/gems/ruby-2.1.5@my_gemset/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
	/Users/michal/.rvm/gems/ruby-2.1.5@my_gemset/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
	/Users/michal/.rvm/gems/ruby-2.1.5@my_gemset/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
	/Users/michal/.rvm/gems/ruby-2.1.5@my_gemset/gems/sinatra-1.4.5/lib/sinatra/base.rb:1073:in `dispatch!'
	/Users/michal/.rvm/gems/ruby-2.1.5@my_gemset/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `block in call!'
	/Users/michal/.rvm/gems/ruby-2.1.5@my_gemset/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
	/Users/michal/.rvm/gems/ruby-2.1.5@my_gemset/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
	/Users/michal/.rvm/gems/ruby-2.1.5@my_gemset/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
	/Users/michal/.rvm/gems/ruby-2.1.5@my_gemset/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `call!'
	/Users/michal/.rvm/gems/ruby-2.1.5@my_gemset/gems/sinatra-1.4.5/lib/sinatra/base.rb:886:in `call'
	/Users/michal/.rvm/gems/ruby-2.1.5@my_gemset/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
	/Users/michal/.rvm/gems/ruby-2.1.5@my_gemset/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
	/Users/michal/.rvm/gems/ruby-2.1.5@my_gemset/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
	/Users/michal/.rvm/gems/ruby-2.1.5@my_gemset/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/Users/michal/.rvm/gems/ruby-2.1.5@my_gemset/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/Users/michal/.rvm/gems/ruby-2.1.5@my_gemset/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
	/Users/michal/.rvm/gems/ruby-2.1.5@my_gemset/gems/rack-1.6.0/lib/rack/nulllogger.rb:9:in `call'
	/Users/michal/.rvm/gems/ruby-2.1.5@my_gemset/gems/rack-1.6.0/lib/rack/head.rb:13:in `call'
	/Users/michal/.rvm/gems/ruby-2.1.5@my_gemset/gems/sinatra-1.4.5/lib/sinatra/base.rb:180:in `call'
	/Users/michal/.rvm/gems/ruby-2.1.5@my_gemset/gems/sinatra-1.4.5/lib/sinatra/base.rb:2014:in `call'
	/Users/michal/.rvm/gems/ruby-2.1.5@my_gemset/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `block in call'
	/Users/michal/.rvm/gems/ruby-2.1.5@my_gemset/gems/sinatra-1.4.5/lib/sinatra/base.rb:1788:in `synchronize'
	/Users/michal/.rvm/gems/ruby-2.1.5@my_gemset/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `call'
	/Users/michal/.rvm/gems/ruby-2.1.5@my_gemset/gems/capybara-2.4.4/lib/capybara/server.rb:19:in `call'
	/Users/michal/.rvm/gems/ruby-2.1.5@my_gemset/gems/rack-1.6.0/lib/rack/handler/webrick.rb:89:in `service'
	/Users/michal/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/webrick/httpserver.rb:138:in `service'
	/Users/michal/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/webrick/httpserver.rb:94:in `run'
	/Users/michal/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'
Braintree::UnexpectedError: expected a gzipped response
from /Users/michal/.rvm/gems/ruby-2.1.5@my_gemset/gems/braintree-2.38.0/lib/braintree/http.rb:100:in `_body'
```

My setup
fake_braintree (0.6.0)
rails (4.2.0)
braintree (2.38.0)
ruby 2.1.5

Please feel free to to ask me for additional info. Thanks in advance guys!

**Comment by gabebw** [comment]
Aha, I think I see the problem - `fake_braintree` assumes that a number is being passed in the `:credit_card` hash (in `fake_braintree/lib/customer.rb`):

```ruby
new_credit_card_hash['bin'] = new_credit_card_hash['number'][0..5]
```

Since there is no number, it's doing `nil[0..5]`, which crashes. `fake_braintree` doesn't support the new nonce-based API, but there's been some effort to support it in #82 and #61.

Sorry, we don't have a fix for this right now.

**Comment by gabebw** [comment]
For now, the best solution is just to hit Braintree's sandbox environment :/

**Comment by CucumisSativus** [comment]
What a pitty, anyway thanks for your time

**Comment by gregblass** [comment]
Does this mean this gem is depreciated with the current braintree API?

**Comment by wacii** [comment]
You can't create credit cards with a payment method nonce through a customer, although you can create both separately.

**Comment by gregblass** [comment]
Hmmm, OK. Is there a way to hit the braintree servers for only tests that use that, and not the others that are supported by fake braintree?

**Comment by gregblass** [comment]
I'd hate to have my tests be a ton slower every time because they have to hit braintree servers. 

Maybe I could re-engineer my app to get around this...like create a customer beforehand, like when a user registers for his account, and get it out of the way. 

But then I'd be creating customers for anyone who registers for a free trail, and creating an account will take longer and hit the braintree servers when it doesn't really need to yet. 

Blah.

**Comment by twalpole** [comment]
@greblass Or you could fork this gem, add the functionality you need, and then submit a PR back :)

**Comment by gregblass** [comment]
I was waiting for that! Typical snarky open source maintainer response.

I doubt I have the skills is the problem.

**Comment by gregblass** [comment]
I may be doing something wrong, but I'm still getting this error, even when just creating a payment method separately from a customer.

Going to just hit braintree servers and deal with the slowness for now. If I can find some time maybe I'll look into helping out here. I'll keep my eye on this from time to time. Maybe mark as not closed?

**Comment by wacii** [comment]
I don't know of a way to selectively turn off the fake, but it seems like it would be easy to do.

There are working examples of `PaymentMethod.create` in the specs. Only advice I can give without sample code.

**Comment by gregblass** [comment]
I just realized another option - Just use transparent redirect instead of braintree.js. I'll just refactor my code to use that until this library has caught up with the new API.

**Comment by gregblass** [comment]
One last thing I'd thought might be the issue - This would work in an RSpec controller right? Or does it have to be a capybara integration test to work?

**Comment by wacii** [comment]
Capybara is required. When you use this library you are still making web requests. They are just intercepted by fake_braintree.

**Comment by gregblass** [comment]
I am using Capybara for my integration tests already, so its configured and available. Here is what I'm getting for Payment::Create (same thing that seems to be happening for the customer create above):

    require 'fake_braintree'
    FakeBraintree.activate!
    result = Braintree::PaymentMethod.create(customer_id: 'abc123', payment_method_nonce: "fake-valid-nonce") 

    Braintree::UnexpectedError: expected a gzipped response


Backtrace:

    NoMethodError - undefined method `merge' for nil:NilClass:
	/Users/gregblass/.rvm/gems/ruby-2.2.2@brewlog/gems/fake_braintree-0.7.0/lib/fake_braintree/sinatra_app.rb:208:in `block in <class:SinatraApp>'
	/Users/gregblass/.rvm/gems/ruby-2.2.2@brewlog/gems/sinatra-1.4.6/lib/sinatra/base.rb:1610:in `call'
	/Users/gregblass/.rvm/gems/ruby-2.2.2@brewlog/gems/sinatra-1.4.6/lib/sinatra/base.rb:1610:in `block in compile!'
	/Users/gregblass/.rvm/gems/ruby-2.2.2@brewlog/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `[]'
	/Users/gregblass/.rvm/gems/ruby-2.2.2@brewlog/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `block (3 levels) in route!'
	/Users/gregblass/.rvm/gems/ruby-2.2.2@brewlog/gems/sinatra-1.4.6/lib/sinatra/base.rb:993:in `route_eval'
	/Users/gregblass/.rvm/gems/ruby-2.2.2@brewlog/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `block (2 levels) in route!'
	/Users/gregblass/.rvm/gems/ruby-2.2.2@brewlog/gems/sinatra-1.4.6/lib/sinatra/base.rb:1014:in `block in process_route'
	/Users/gregblass/.rvm/gems/ruby-2.2.2@brewlog/gems/sinatra-1.4.6/lib/sinatra/base.rb:1012:in `catch'
	/Users/gregblass/.rvm/gems/ruby-2.2.2@brewlog/gems/sinatra-1.4.6/lib/sinatra/base.rb:1012:in `process_route'
	/Users/gregblass/.rvm/gems/ruby-2.2.2@brewlog/gems/sinatra-1.4.6/lib/sinatra/base.rb:972:in `block in route!'
	/Users/gregblass/.rvm/gems/ruby-2.2.2@brewlog/gems/sinatra-1.4.6/lib/sinatra/base.rb:971:in `each'
	/Users/gregblass/.rvm/gems/ruby-2.2.2@brewlog/gems/sinatra-1.4.6/lib/sinatra/base.rb:971:in `route!'
	/Users/gregblass/.rvm/gems/ruby-2.2.2@brewlog/gems/sinatra-1.4.6/lib/sinatra/base.rb:1084:in `block in dispatch!'
	/Users/gregblass/.rvm/gems/ruby-2.2.2@brewlog/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `block in invoke'
	/Users/gregblass/.rvm/gems/ruby-2.2.2@brewlog/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `catch'
	/Users/gregblass/.rvm/gems/ruby-2.2.2@brewlog/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `invoke'
	/Users/gregblass/.rvm/gems/ruby-2.2.2@brewlog/gems/sinatra-1.4.6/lib/sinatra/base.rb:1081:in `dispatch!'
	/Users/gregblass/.rvm/gems/ruby-2.2.2@brewlog/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `block in call!'
	/Users/gregblass/.rvm/gems/ruby-2.2.2@brewlog/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `block in invoke'
	/Users/gregblass/.rvm/gems/ruby-2.2.2@brewlog/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `catch'
	/Users/gregblass/.rvm/gems/ruby-2.2.2@brewlog/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `invoke'
	/Users/gregblass/.rvm/gems/ruby-2.2.2@brewlog/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `call!'
	/Users/gregblass/.rvm/gems/ruby-2.2.2@brewlog/gems/sinatra-1.4.6/lib/sinatra/base.rb:894:in `call'
	/Users/gregblass/.rvm/gems/ruby-2.2.2@brewlog/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
	/Users/gregblass/.rvm/gems/ruby-2.2.2@brewlog/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
	/Users/gregblass/.rvm/gems/ruby-2.2.2@brewlog/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
	/Users/gregblass/.rvm/gems/ruby-2.2.2@brewlog/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/Users/gregblass/.rvm/gems/ruby-2.2.2@brewlog/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/Users/gregblass/.rvm/gems/ruby-2.2.2@brewlog/gems/rack-1.6.4/lib/rack/nulllogger.rb:9:in `call'
	/Users/gregblass/.rvm/gems/ruby-2.2.2@brewlog/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
	/Users/gregblass/.rvm/gems/ruby-2.2.2@brewlog/gems/sinatra-1.4.6/lib/sinatra/base.rb:181:in `call'
	/Users/gregblass/.rvm/gems/ruby-2.2.2@brewlog/gems/sinatra-1.4.6/lib/sinatra/base.rb:2021:in `call'
	/Users/gregblass/.rvm/gems/ruby-2.2.2@brewlog/gems/sinatra-1.4.6/lib/sinatra/base.rb:1486:in `block in call'
	/Users/gregblass/.rvm/gems/ruby-2.2.2@brewlog/gems/sinatra-1.4.6/lib/sinatra/base.rb:1795:in `synchronize'
	/Users/gregblass/.rvm/gems/ruby-2.2.2@brewlog/gems/sinatra-1.4.6/lib/sinatra/base.rb:1486:in `call'
	/Users/gregblass/.rvm/gems/ruby-2.2.2@brewlog/gems/capybara-2.4.4/lib/capybara/server.rb:19:in `call'
	/Users/gregblass/.rvm/gems/ruby-2.2.2@brewlog/gems/rack-1.6.4/lib/rack/handler/webrick.rb:88:in `service'
	/Users/gregblass/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
	/Users/gregblass/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
	/Users/gregblass/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'
    Braintree::UnexpectedError: expected a gzipped response

So, if this is just a matter of me not using the new braintree.js API and using the older Transparent Redirect API, then no worries, I'll downgrade my code so that I can test it. That should be the case, correct?

**Comment by wacii** [comment]
The nonce is meaningful, you can't just provided garbage.

You either have to create the nonce normally through the client, or use `FakeBraintree::PaymentMethod.tokenize_card`.

**Comment by gregblass** [comment]
Gotcha. I thought that "fake-valid-nonce" was the same as Braintree::Test::Nonce::Transactable, which seemed kosher from the first example in this issue. Check out here: https://developers.braintreepayments.com/ios+ruby/reference/general/testing

So if you open up a console and type

    Braintree::Test::Nonce::Transactable

you'll get:
 
    => "fake-valid-nonce" 

So you're saying I can't use that? Any reason its OK to use in the first example here?

**Comment by wacii** [comment]
That's a guide for testing against the sandbox environment. There's testing data already built in to that. Not so with fake_braintree.

**Comment by gregblass** [comment]
Ahhh. Thank you so much for clarifying.

Really it clicked for me by looking here: https://github.com/highfidelity/fake_braintree/blob/530502c59af4c35e4e23e8505c2bb6192855a31e/spec/fake_braintree/transparent_redirect_spec.rb

I can see how this is really intended to be used by looking at these specs.

Thanks for all your help!
